schema_file_path: configs/schema_training.json
raw_input: artifacts/raw_input

artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  good_files: artifacts/data_ingestion/good_files
  bad_files: artifacts/data_ingestion/bad_files
  cummilated_csv: artifacts/data_ingestion/cummilated_csv
  archive_bad_files: artifacts/data_ingestion/archive_bad_files
  training_local_db: artifacts/local_db/training_local_db
  prediction_local_db: artifacts/local_db/prediction_local_db

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5