grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: Ridge
    module: sklearn.linear_model
    search_param_grid:
      alpha:
      - 1.0e-08
      - 0.0001
      - 0.01
      - 1
      - 5
      - 10
      - 20
      - 40
      - 80
      fit_intercept:
      - true
      - false
  module_2:
    class: Lasso
    module: sklearn.linear_model
    search_param_grid:
      alpha:
      - 1.0e-08
      - 0.0001
      - 0.01
      - 1
      - 5
      - 10
      - 20
      - 40
      - 80
      fit_intercept:
      - true
      - false
  module_3:
    class: ElasticNet
    module: sklearn.linear_model
    search_param_grid:
      alpha:
      - 1.0e-08
      - 0.0001
      - 0.01
      - 1
      - 5
      - 10
      - 20
      - 40
      - 80
      fit_intercept:
      - true
      - false
      l1_ratio:
      - 1.0e-11
      - 1.0e-06
      - 0.001
      - 1
      - 5
      - 10
      - 20
      - 50
      - 70
      - 80
      - 100
  module_4:
    class: DecisionTreeRegressor
    module: sklearn.tree
    search_param_grid:
      min_samples_leaf:
      - 1
      - 2
      - 3
      - 4
      - 5
  module_5:
    class: RandomForestRegressor
    module: sklearn.ensemble
    search_param_grid:
      criterion:
      - squared_error
      - absolute_error
      - poisson
      max_depth:
      - 3
      - 5
      - 7
      - 10
      - 15
      - 25
  module_6:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    search_param_grid:
      criterion:
      - friedman_mse
      - squared_error
      loss:
      - squared_error
      - absolute_error
      - huber
      - quantile
